[package]
name = "web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2", features = ["tokio"] }
tokio = { version = "1.39.2", features = ["full"] }
anyhow = "1.0"
tensorflow = "0.21.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ahash = "0.8.11"
